"""empty message

Revision ID: 25df233f2a1e
Revises: 64473626bbb6
Create Date: 2022-07-19 01:13:56.798527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25df233f2a1e'
down_revision = '64473626bbb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
